name: Build Python Application

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  build:
    runs_on: ubuntu_latest

    steps:
      - name: Checkout the code
        uses: actions/
